# baseurl = "https://EveryoneProgram.github.io"
baseurl = "http://EveryoneProgram.com"
languageCode = "en-us"
title = "Everyone Program: A free, self-paced, coached introduction to computer programming for people who know nothing about it."
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	# author = "Bruce Eckel"
	description = "A free, self-paced, coached introduction to computer programming for people who know nothing about it."

	logo = "/images/EveryoneProgramCircle.png"
	favicon = "images/ep-favicon.png"
	banner_image = "/images/EveryoneProgramBanner.jpg"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "orange"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = ""
	email   = "mindviewinc@gmail.com"

[[menu.main]]
	name   = "How It Works"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "The Tutorials"
	url    = "tutorials/"
	weight = 20

[[menu.main]]
	name   = "Videos"
	url    = "videos/"
	weight = 30

[[menu.main]]
	name   = "How to Join"
	url    = "joining/"
	weight = 40

[[menu.main]]
	name   = "More Resources"
	url    = "resources/"
	weight = 50


[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 100


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
